name: _fe_analyzer_shared
version: 40.0.0
description: Logic that is shared between the front_end and analyzer packages.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/_fe_analyzer_shared

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.0.2

dev_dependencies:
  test: ^1.3.4
